# Generated by Django 2.2.14 on 2022-06-15 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='slug',
            new_name='slug2',
        ),
    ]
