# Generated by Django 2.2.14 on 2022-06-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='amount',
            new_name='quantity',
        ),
    ]
