# Generated by Django 2.2.14 on 2022-06-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_payment'),
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
    ]
